language_learning_platform/routes/auth.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse
from language_learning_platform.models.models import db, User
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__, url_prefix='/auth')

@auth.route('/profile')
@login_required
def profile():
    return render_template('profile.html', name=current_user.username)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email address already exists')
            return redirect(url_for('auth.register'))

        hashed_password = generate_password_hash(password, method='sha256')
        new_user = User(name=name, email=email, password=hashed_password, role='admin')
        db.session.add(new_user)
        db.session.commit()

        flash('Registration successful, please log in')

        # Log out the current user before redirecting to the login page
        logout_user()
        return redirect(url_for('auth.login'))

    return render_template('register.html')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(email=email).first()

        if user is None:
                flash('Login Unsuccessful. Please check your email and password', 'danger')
                return redirect(url_for('auth.login'))
        elif user.check_password(password):
            print("Logging in as User:", user)
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('home'))
        else:
            flash('Login Unsuccessful. Please check your email and password', 'danger')

    return render_template('login.html')


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('home'))

language_learning_platform/routes/grammar.py
# routes/grammar.py
from flask import Blueprint, request, render_template, redirect, url_for
from flask_login import login_required
from language_learning_platform.models.models import db, Grammar
from sqlalchemy.sql.expression import func
from flask import jsonify
import json

grammar = Blueprint('grammar', __name__, url_prefix='/grammar')

@grammar.route('/', methods=['GET', 'POST'])
@login_required
def grammar_page():
    if request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')
        gram = Grammar(title=title, description=description)
        db.session.add(gram)
        db.session.commit()
        return redirect(url_for('grammar.grammar_page'))

    reminder_item = Grammar.query.order_by(func.random()).first()
    # Get all Grammar items
    grammar_items = Grammar.query.all()

    # Convert the items to a list of dictionaries
    grammar_items = [
        {
            'id': item.id,
            'title': item.title,
            'description': item.description,
            'mastery': item.mastery
        }
        for item in grammar_items
    ]

    # Convert the list to JSON
    grammar_items_json = json.dumps(grammar_items)

    return render_template('grammar.html', reminder_item=reminder_item, grammar_items_json=grammar_items_json)

@grammar.route('/update/<int:id>', methods=['POST'])
@login_required
def update_grammar(id):
    title = request.form.get('title')
    description = request.form.get('description').replace('\r\n', '\n')
    gramm = Grammar.query.get(id)
    if gramm:
        gramm.title = title
        gramm.description = description
        db.session.commit()
    return redirect(url_for('grammar.all_grammar'))

@grammar.route('/delete/<int:id>', methods=['POST'])
@login_required
def delete_grammar(id):
    gramm = Grammar.query.get(id)
    if gramm:
        db.session.delete(gramm)
        db.session.commit()
    return redirect(url_for('grammar.all_grammar'))

@grammar.route('/all', methods=['GET'])
@login_required
def all_grammar():
    gramm_items = Grammar.query.all()
    return render_template('all_grammar.html', items=gramm_items)

@grammar.route('/api', methods=['GET'])
def api_grammar():
    gramm_items = Grammar.query.all()
    return jsonify([item.to_dict() for item in gramm_items])

language_learning_platform/routes/image.py
# routes/image.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_login import login_required
from language_learning_platform.models.models import db, Image
from sqlalchemy.sql.expression import func
from werkzeug.utils import secure_filename
from flask import jsonify
import os
import json

image = Blueprint('image', __name__, url_prefix='/image')

UPLOAD_FOLDER = 'uploads/images'
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif', 'pdf'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@image.route('/', methods=['GET', 'POST'])
@login_required
def image_page():
    if request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')
        image_file = request.files['image']
        filename = secure_filename(image_file.filename)  # use secure_filename to ensure a safe filename
        if allowed_file(filename):
            upload_folder = os.path.join(current_app.root_path, current_app.config['UPLOAD_FOLDER'])
            os.makedirs(upload_folder, exist_ok=True)
            image_path = os.path.join(upload_folder, filename)
            image_file.save(image_path)
            img = Image(title=title, description=description, image_filename=filename)  # pass the filename, not the path
            db.session.add(img)
            db.session.commit()
        return redirect(url_for('image.image_page'))
    reminder_item = Image.query.order_by(func.random()).first()
    if reminder_item:
        file_type = 'pdf' if reminder_item.image_filename.rsplit('.', 1)[1].lower() == 'pdf' else 'image'
    else:
        file_type = 'image'
    # Get all Image items
    image_items = Image.query.all()

    # Convert the items to a list of dictionaries
    image_items = [item.to_dict() for item in image_items]

    # Convert the list to JSON
    image_items_json = json.dumps(image_items)

    return render_template('image.html', reminder_item=reminder_item, image_items_json=image_items_json, file_type=file_type)

@image.route('/all_image', methods=['GET'])
def all_image():
    image_items = Image.query.all()
    return render_template('all_image.html', items=image_items)

@image.route('/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update_image(id):
    img = Image.query.get(id)
    if request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')
        image_file = request.files.get('image')  # Here we get the new image from the form
        if image_file:
            filename = secure_filename(image_file.filename)
            upload_folder = os.path.join(current_app.root_path, current_app.config['UPLOAD_FOLDER'])
            os.makedirs(upload_folder, exist_ok=True)
            image_path = os.path.join(upload_folder, filename)
            image_file.save(image_path)
            img.image_filename = filename  # If a new image was uploaded, we update the filename in the database
        if title:
            img.title = title
        if description:
            img.description = description
        db.session.commit()
        return redirect(url_for('image.all_image'))
    return render_template('update_image.html', image=img)

@image.route('/delete/<int:id>', methods=['POST'])
@login_required
def delete_image(id):
    img = Image.query.get(id)
    if img:
        db.session.delete(img)
        db.session.commit()
    return redirect(url_for('image.all_image'))

@image.route('/api/image', methods=['GET'])
@login_required
def api_image():
    image_items = Image.query.all()
    return jsonify([item.to_dict() for item in image_items])

language_learning_platform/routes/vocabulary.py
from flask import Blueprint, request, render_template, redirect, url_for
from flask_login import login_required
#from language_learning_platform.models import Vocabulary
from language_learning_platform.models.models import db, Vocabulary
from sqlalchemy.sql.expression import func
from flask import jsonify
import json

vocabulary = Blueprint('vocabulary', __name__, url_prefix='/vocabulary')

@vocabulary.route('/', methods=['GET', 'POST'])
@login_required
def vocabulary_page():
    if request.method == 'POST':
        title = request.form.get('title')
        description = request.form.get('description')
        vocab = Vocabulary(title=title, description=description)
        db.session.add(vocab)
        db.session.commit()
        return redirect(url_for('vocabulary.vocabulary_page'))

    reminder_item = Vocabulary.query.order_by(func.random()).first()
    # Get all vocabulary items
    vocabulary_items = Vocabulary.query.all()

    # Convert the items to a list of dictionaries manually
    vocabulary_items = [
        {
            'id': item.id,
            'title': item.title,
            'description': item.description,
            'mastery': item.mastery
        }
        for item in vocabulary_items
    ]

    # Convert the list to JSON using Flask's jsonify()
    vocabulary_items_json = json.dumps(vocabulary_items)

    return render_template('vocabulary.html', reminder_item=reminder_item, vocabulary_items_json=vocabulary_items_json)

@vocabulary.route('/update/<int:id>', methods=['POST'])
@login_required
def update_vocabulary(id):
    title = request.form.get('title')
    description = request.form.get('description').replace('\r\n', '\n')
    vocab = Vocabulary.query.get(id)
    if vocab:
        vocab.title = title
        vocab.description = description
        db.session.commit()
    return redirect(url_for('vocabulary.all_vocabulary'))

@vocabulary.route('/delete/<int:id>', methods=['POST'])
@login_required
def delete_vocabulary(id):
    vocab = Vocabulary.query.get(id)
    if vocab:
        db.session.delete(vocab)
        db.session.commit()
    return redirect(url_for('vocabulary.all_vocabulary'))

@vocabulary.route('/all', methods=['GET'])
@login_required
def all_vocabulary():
    vocab_items = Vocabulary.query.all()
    return render_template('all_vocabulary.html', items=vocab_items)

@vocabulary.route('/api', methods=['GET'])
@login_required
def api_vocabulary():
    vocab_items = Vocabulary.query.all()

    # Convert the items to a list of dictionaries manually
    vocabulary_items = [
        {
            'id': item.id,
            'title': item.title,
            'description': item.description,
            'mastery': item.mastery
        }
        for item in vocab_items
    ]

    # Convert the list to JSON using Flask's jsonify()
    vocabulary_items_json = jsonify(vocabulary_items)

    return vocabulary_items_json

templates/all_grammar.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        background-color: black;
    }
    .item-card {
        background-color: #ff6347;
        border-radius: 20px;
        padding: 20px;
        margin-bottom: 20px;
        color: white;
    }

    .button {
        background-color: #008CBA;
        border: none;
        color: white;
        padding: 14px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 50px;
    }

    .item-form {
        margin-bottom: 20px;
    }

    .item-form input[type=text],
    .item-form textarea {
        width: 100%;
        padding: 8px 12px; /* Adjust the padding as desired */
        margin: 4px 0;
        box-sizing: border-box;
        border: none;
        border-radius: 4px;
    }

    .item-form input[type=submit] {
        background-color: #120236;
        color: white;
        padding: 10px 16px; /* Adjust the padding as desired */
        margin: 4px 0;
        border: none;
        border-radius: 50px;
        cursor: pointer;
        font-size: 14px; /* Adjust the font size as desired */
    }
</style>

<div style="text-align: center; margin-right: 20px;"> <!-- Moves the title "grammar" to the right -->
    <h1 style="color: #080808;">All grammar Items</h1> <!-- Changes title color -->
</div>
{% for item in items %}
    <div class="item-card">
        <h2>{{ item.title }}</h2>
        <p>{{ item.description }}</p>
        <p>Mastery: {{ item.mastery }}</p>

        <div class="item-form">
            <form method="POST" action="{{ url_for('grammar.update_grammar', id=item.id) }}">
                <input type="text" name="title" value="{{ item.title }}" required>
                <textarea name="description" required>{{ item.description }}</textarea>
                <input type="submit" value="Update">
            </form>
        </div>

        <form method="POST" action="{{ url_for('grammar.delete_grammar', id=item.id) }}">
            <input class="button" type="submit" value="Delete">
        </form>
    </div>
{% endfor %}
<a href="{{ url_for('grammar.grammar_page') }}" class="button">Go Back to grammar Page</a>
{% endblock %}

templates/all_image.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        background-color: black;
    }
    .item-card {
        background-color: #ff6347;
        border-radius: 20px;
        padding: 20px;
        margin-bottom: 20px;
        color: white;
    }

    .button {
        background-color: #008CBA;
        border: none;
        color: white;
        padding: 14px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 50px;
    }

    .item-form {
        margin-bottom: 20px;
    }

    .item-form input[type=text],
    .item-form textarea {
        width: 100%;
        padding: 8px 12px; /* Adjust the padding as desired */
        margin: 4px 0;
        box-sizing: border-box;
        border: none;
        border-radius: 4px;
    }

    .item-form input[type=submit] {
        background-color: #120236;
        color: white;
        padding: 10px 16px; /* Adjust the padding as desired */
        margin: 4px 0;
        border: none;
        border-radius: 50px;
        cursor: pointer;
        font-size: 14px; /* Adjust the font size as desired */
    }
</style>

<div style="text-align: center; margin-right: 20px;"> 
    <h1 style="color: #080808;">All Image Items</h1> <!-- Changes title color -->
</div>

{% for item in items %}
    <div class="item-card">
        <h2>{{ item.title }}</h2>
        <p>{{ item.description }}</p>
        <img src="{{ url_for('static', filename=item.image_path) }}" alt="Image">
        <p>Mastery: {{ item.mastery }}</p>

        <div class="item-form">
            <form method="POST" action="{{ url_for('image.update_image', id=item.id) }}" enctype="multipart/form-data">
                <input type="text" name="title" value="{{ item.title }}" required>
                <textarea name="description" required>{{ item.description }}</textarea>
                <input type="file" name="image" accept="image/*">
                <input type="submit" value="Update">
            </form>
        </div>

        <form method="POST" action="{{ url_for('image.delete_image', id=item.id) }}">
            <input class="button" type="submit" value="Delete">
        </form>
    </div>
{% endfor %}
<a href="{{ url_for('image.image_page') }}" class="button">Go Back to Image Page</a>
{% endblock %}

templates/all_vocabulary.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        background-color: black;
    }
    .item-card {
        background-color: #ff6347;
        border-radius: 20px;
        padding: 20px;
        margin-bottom: 20px;
        color: white;
    }

    .button {
        background-color: #008CBA;
        border: none;
        color: white;
        padding: 14px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 50px;
    }

    .item-form {
        margin-bottom: 20px;
    }

    .item-form input[type=text],
    .item-form textarea {
        width: 100%;
        padding: 8px 12px; /* Adjust the padding as desired */
        margin: 4px 0;
        box-sizing: border-box;
        border: none;
        border-radius: 4px;
    }

    .item-form input[type=submit] {
        background-color: #120236;
        color: white;
        padding: 10px 16px; /* Adjust the padding as desired */
        margin: 4px 0;
        border: none;
        border-radius: 50px;
        cursor: pointer;
        font-size: 14px; /* Adjust the font size as desired */
    }
</style>

<div style="text-align: center; margin-right: 20px;"> <!-- Moves the title "Vocabulary" to the right -->
    <h1 style="color: #080808;">All Vocabulary Items</h1> <!-- Changes title color -->
</div>
{% for item in items %}
    <div class="item-card">
        <h2>{{ item.title }}</h2>
        <p>{{ item.description|replace('\n', '<br>')|safe }}</p>
        <p>Mastery: {{ item.mastery }}</p>

        <div class="item-form">
            <form method="POST" action="{{ url_for('vocabulary.update_vocabulary', id=item.id) }}">
                <input type="text" name="title" value="{{ item.title }}" required>
                <textarea name="description" required>{{ item.description }}</textarea>
                <input type="submit" value="Update">
            </form>
        </div>

        <form method="POST" action="{{ url_for('vocabulary.delete_vocabulary', id=item.id) }}">
            <input class="button" type="submit" value="Delete">
        </form>
    </div>
{% endfor %}
<a href="{{ url_for('vocabulary.vocabulary_page') }}" class="button">Go Back to Vocabulary Page</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Language Learning App</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/category.html
{% extends "base.html" %}

{% block content %}
    <h2 id="category-title"></h2>
    <div id="item-container">
        <!-- Items will be inserted here by JavaScript -->
    </div>
    <button id="previous">Previous</button>
    <button id="next">Next</button>
    <button id="back">Back to Dashboard</button>
{% endblock %}

templates/grammar.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        background-color: black;
        background-position: bottom right;
        background-repeat: no-repeat;
        background-size: 100px;
    }

    .grammar-card {
        background-color: #080a28;
        border-radius: 20px;
        padding: 20px;
        margin-bottom: 20px;
        color: white;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.5);
    }

    .grammar-item {
        font-size: 46px;
        font-weight: bold;
        text-align: left;
        margin-bottom: 20px;
    }

    .grammar-description {
        font-size: 18px;
        color: white;
        text-align: left;
    }

    .tilted-image {
        position: absolute;
        right: 100px; /* Adjust the right position as desired */
        bottom: 100px; /* Adjust the bottom position as desired */
        transform: rotate(-10deg); /* Adjust the tilt angle as desired */
        opacity: 0.8; /* Adjust the opacity as desired */
        width: 650px; /* Adjust the width as desired */
        height: 250px; /* Adjust the height as desired */
    }

    .form-container {
        background-color: #f0d4d4;
        border-radius: 20px;
        padding: 10px;
        margin-bottom: 0px; /* add this to push the navigation links down */
        position: absolute;
        left: 20px; /* Adjust the left position as desired */
        bottom: 150px; /* Adjust the bottom position as desired */
    }

    .form-container input[type=text],
    .form-container textarea {
        width: 100%;
        padding: 8px 12px; /* Adjust the padding as desired */
        margin: 4px 0;
        box-sizing: border-box;
        border: none;
        border-radius: 4px;
    }

    .form-container input[type=submit] {
        background-color: #120236;
        color: white;
        padding: 10px 16px; /* Adjust the padding as desired */
        margin: 4px 0;
        border: none;
        border-radius: 50px;
        cursor: pointer;
        font-size: 14px; /* Adjust the font size as desired */
    }

    .circle {
        width: 70px;
        height: 70px;
        background-color: #ff6347;
        border-radius: 50%;
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 20px;
    }

    .circle-container {
        position: relative;
        width: 100%;
        display: flex;
        justify-content: flex-start;
        padding: 10px;
    }


    .circle-container a {
        text-decoration: none;
    }

    .circle-container h2 {
        color: white;
        font-size: 12px; /* Adjust the font size as desired */
        margin-top: 4px; /* Adjust the margin as desired */
    }

    .circle-container .circle {
        transition: transform 0.2s;
        cursor: pointer;
    }

    .circle-container .circle:hover {
        transform: scale(1.1);
    }

    .content-wrapper {
        min-height: 100vh; /* Set the minimum height to the full viewport height */
        display: flex; /* Set up a flexbox layout */
        flex-direction: column; /* Stack the content vertically */
        justify-content: space-between; /* Put as much space as possible between items */
    }
</style>
<div class="content-wrapper">
    <div style="text-align: center; margin-top: 20px;">
        <h1 class="grammar-item" style="font-family: 'Comic Sans MS', cursive; color: rgb(250, 248, 248);">
            {% if reminder_item %}{{ reminder_item.title }}{% endif %}
        </h1>
        <p class="grammar-description">
            {% if reminder_item %}{{ reminder_item.description|replace('\r\n', '<br>')|safe  }}{% endif %}
        </p>
        <img class="tilted-image" src="/static/images/sweden_flag2.jpg" alt="Swedish Flag">
    </div>

    <div class="form-container" style="display: none;">
        <form method="POST" enctype="multipart/form-data">
            <input type="text" name="title" placeholder="Title" required>
            <textarea name="description" placeholder="Description" required></textarea>
            <input type="submit" value="Add">
        </form>
    </div>   

    <div class="circle-container">
        <div class="circle" id="nextButton">
            <h2>Next Item</h2>
        </div>
        <div class="circle" onclick="toggleFormContainer(event);">
            <h2>Add Item</h2>
        </div>
        <a href="{{ url_for('grammar.all_grammar') }}">
            <div class="circle">
                <h2>All items</h2>
            </div>
        </a>
        <a href="{{ url_for('home') }}">
            <div class="circle">
                <h2>Home</h2>
            </div>
        </a>
    </div>
</div>
<script>
    var grammarItemsJSON = {{ grammar_items_json|safe }};
</script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        var formContainer = document.querySelector('.form-container');
        var form = document.querySelector('.form-container form');
        form.addEventListener('click', function (event) {
            event.stopPropagation();
        });

        window.toggleFormContainer = function(event) {
            event.stopPropagation();
            formContainer.style.display = formContainer.style.display === 'none' ? 'block' : 'none';
        }

        document.addEventListener('click', function (event) {
            if (formContainer.style.display === 'block') {
                formContainer.style.display = 'none';
            }
        });

        var grammarItems = grammarItemsJSON;
        var titleElement = document.querySelector('.grammar-item');
        var descriptionElement = document.querySelector('.grammar-description');

        function updateGrammarItem() {
            // Get a random index
            var randomIndex = Math.floor(Math.random() * grammarItems.length);

            // Get the item at the random index
            var item = grammarItems[randomIndex];

            // Update the title, description and grammar.
            titleElement.textContent = item.title;
            descriptionElement.innerText = item.description;
        }

        updateGrammarItem();

        var nextButton = document.getElementById('nextButton');
        nextButton.addEventListener('click', function () {
            updateGrammarItem();
        });
    });
</script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        background-color: black;
    }

    .circle {
        width: 200px;
        height: 200px;
        background-color: #ff6347;
        border-radius: 50%;
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 20px;
    }

    .circle_logout {
        width: 40px;
        height: 40px;
        background-color: #fdfdfd;
        border-radius: 50%;
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0px;
        position: absolute;
        left: 20px;
        /* Adjust the left position as desired */
        bottom: 50px;
    }

    .circle-container {
        display: flex;
        justify-content: center;
        margin-top: 100px;
    }

    .circle a {
        color: white;
        text-decoration: none;
    }

    .circle-text {
        margin-top: 25px;
        color: white; /* Add this line to change the color of the text */
    }

    #vocabulary-text {
        margin-left: 0px;
        color: white;
    }

    #grammar-text {
        margin-left: 0px;
        color: white;
    }

    #image-text {
        margin-left: 0px;
        color: white;
    }

    #logout-text {
        margin-left: 0px;
        margin-right: 2px;
        color: #ff6347;
        font-size: 14px;
        margin-top: 15px;
    }


</style>

<div class="circle-container">
    <a href="{{ url_for('vocabulary.vocabulary_page') }}">
        <div class="circle">
            <h2><p class="circle-text" id="vocabulary-text">Vocabulary</p></h2>
        </div>
        <!--<p class="circle-text" id="vocabulary-text">Learn new words and phrases</p>-->
    </a>
    <a href="{{ url_for('grammar.grammar_page') }}">
        <div class="circle">
            <h2><p class="circle-text" id="grammar-text">Grammar</p></h2>
        </div>
        <!-- Added the id "grammar-text" here -->
        <!--<p class="circle-text" id="grammar-text">Learn grammar rules</p>-->
    </a>
    <a href="{{ url_for('image.image_page') }}">
        <div class="circle">
            <h2><p class="circle-text" id="image-text">Image</p></h2>
        </div>
        <!--<p class="circle-text" id="image-text">Learn from images</p>-->
    </a>
</div>

<div class="circle-container"></div>
<a href="{{ url_for('auth.logout') }}">
    <div class="circle_logout">
        <h2><p class="circle-text" id="logout-text">Out</p></h2>
    </div>
    <!--<p class="circle-text" id="vocabulary-text">Learn new words and phrases</p>-->
</a>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        background-color: black;
    }

    .container {
        margin-top: 100px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        color: white;
    }

    .form-group {
        margin-bottom: 20px;
        width: 300px;
    }

    .form-control {
        width: 100%;
        padding: 10px;
        border: none;
        border-radius: 4px;
        background-color: #313130;
        color: white;
    }

    .form-check-input {
        margin-right: 10px;
    }

    .btn-primary {
        background-color: #ff6347;
        border: none;
        color: white;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        cursor: pointer;
        border-radius: 4px;
    }

    p {
        margin-top: 10px;
    }

    a {
        color: #ff6347;
        text-decoration: none;
    }

    .flashes {
        list-style: none;
        padding: 0;
        margin: 0;
    }

    .error {
        color: red;
    }
</style>

<div class="container">
    <h1>Login</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="flashes">
                {% for message in messages %}
                    <li{% if 'error' in message %} class="error"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    <form method="post" action="{{ url_for('auth.login') }}" class="mb-3">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" name="email" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" name="password" class="form-control" required>
        </div>
        <div class="form-check">
            <input type="checkbox" name="remember" class="form-check-input" id="remember">
            <label class="form-check-label" for="remember">Remember me</label>
        </div>
        <input type="submit" value="Login" class="btn btn-primary mt-2">
    </form>
    <p>Don't have an account? <a href="{{ url_for('auth.register') }}">Register</a></p>
</div>
{% endblock %}